name: projet_medical_management_flutter
description: "medical_management"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.0
  sqflite: ^2.3.2
  path: ^1.9.0
  uuid: ^4.0.0
  connectivity_plus: ^6.0.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/nom_de_l_image.png
    - assets/icon/app_icon.png