// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxB7rJkMomfu8s5jEchNtuyklvtHhcaOw',
    appId: '1:596270167480:web:66d3ee8001266274098b4d',
    messagingSenderId: '596270167480',
    projectId: 'projet-medical-management-fl',
    authDomain: 'projet-medical-management-fl.firebaseapp.com',
    storageBucket: 'projet-medical-management-fl.firebasestorage.app',
    measurementId: 'G-EHW801C5HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Txs9-Ctqguzb03V95ih8jhcMbVQ_WUA',
    appId: '1:596270167480:android:1a2a822ea11d8a16098b4d',
    messagingSenderId: '596270167480',
    projectId: 'projet-medical-management-fl',
    storageBucket: 'projet-medical-management-fl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1fb4MJ9BWM7OcaBI-wyRXmIQ8DloY5E',
    appId: '1:596270167480:ios:dc4f387d4083fb24098b4d',
    messagingSenderId: '596270167480',
    projectId: 'projet-medical-management-fl',
    storageBucket: 'projet-medical-management-fl.firebasestorage.app',
    iosBundleId: 'com.example.projetMedicalManagementFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb1fb4MJ9BWM7OcaBI-wyRXmIQ8DloY5E',
    appId: '1:596270167480:ios:dc4f387d4083fb24098b4d',
    messagingSenderId: '596270167480',
    projectId: 'projet-medical-management-fl',
    storageBucket: 'projet-medical-management-fl.firebasestorage.app',
    iosBundleId: 'com.example.projetMedicalManagementFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxB7rJkMomfu8s5jEchNtuyklvtHhcaOw',
    appId: '1:596270167480:web:e30b961ce5f7a031098b4d',
    messagingSenderId: '596270167480',
    projectId: 'projet-medical-management-fl',
    authDomain: 'projet-medical-management-fl.firebaseapp.com',
    storageBucket: 'projet-medical-management-fl.firebasestorage.app',
    measurementId: 'G-MVCLX1NHYD',
  );
}
